apiVersion: v1
kind: Service
metadata:
  name: node todo app-service
  namespace: project-820120f1-fd46-4012-bd42-09b7bf997412
spec:
  selector:
    app: node todo app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
